# Generated by Django 5.2 on 2025-04-13 06:54

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(101)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[users.validators.validate_avatar_size], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in the format: +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
