# Generated by Django 5.2 on 2025-05-04 12:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', validators=[core.validators.validate_image_file_size], verbose_name='Course Image'),
        ),
    ]
